name: Pipeline Completo - Prova DevOps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
jobs:
  mostrar_hora:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir hora do push
        run: |
          echo "Data e hora do último push:"
          date -u +"%Y-%m-%d %H:%M:%S %Z"
            
  deploy:
    needs: mostrar_hora
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
